server :
  port : 8000
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: themef1b4!

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true


spring :
  application :
    name : apigateway
  cloud :
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://k7c2031.p.ssafy.io/"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
      routes:
        - id : user
          uri: lb://user/
          predicates :
            - Path=/user/**
          filters:
            - CustomAuthFilter
        - id: theme
          uri: lb://theme/
          predicates:
            - Path=/theme/**

        - id: feed
          uri: lb://feed/
          predicates:
            - Path=/feed/**

