server :
  port : 8761
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: themef1b4!


spring :
  application :
    name : eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
